### ISSUE TITLE
TOC显示溢出

### ISSUE THREAD

**Issue by Usercyk** [chonext/blog#70]
在 https://blog.yangchaoyi.vip/blog/11-qq-music 中目录部分的显示溢出了屏幕，就算电脑拉到最大都看不见
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/109349977/233041748-71f2ed75-6c0a-406b-8772-ce55665a841c.png">

**Comment by Usercyk** [comment]
手动将浏览器缩小至80%才可以看见

**Comment by Chocolate1999** [comment]
新重构页面后注意适配了，如果还有问题的话，可以提供一下你的电脑屏幕尺寸哈
